<P> <img src="https://i.ibb.co/gyNf19D/nhslogo.png" alt="nhslogo" border="0" width="100" align="right"><font size="6"><b> CS4132 Data Analytics</b> </font>

# Lab 3.2: Pandas

### Submission Instructions

* Complete the following questions and upload your `.ipynb` file to Coursemology.
* Name the file in the following format: `Lab<num><YourName>.ipynb`
* Before submitting, please ensure you click on "Kernel" > "Restart and Run All" on your jupyter notebook. 
* Finally, print a copy of your final solution to OneNote > Your Individual Student Notebook > Labs. Name the page `Lab <num>`.

<div class="alert alert-block alert-danger">
You should harness the power of pandas operations in this lab. 

You are NOT allowed to use `for` loop (including list comprehension) in all questions.
</div>

### Q1

We will use the wine data as discussed in the notes for this lab.

In [ ]:
import numpy as np
def findPlayerPerformance(max_scores, player_scores):    
    test = player_scores / max_scores * 100
    return np.around(np.concatenate((np.array(((test[:, 0] + test[:, 1]) / 2).reshape(((test[:, 0] + test[:, 1]) / 2).shape[0], 1)), np.array(test[:, 2].reshape(test[:, 2].shape[0], 1))), axis = 1), 2)


In [135]:
import pandas as pd
reviews = pd.read_csv("wine.csv", index_col=0) #read in data from wine.csv
reviews.head() #display the first few data from the dataframe

country                                        description  \
0     Italy  Aromas include tropical fruit, broom, brimston...   
1  Portugal  This is ripe and fruity, a wine that is smooth...   
2        US  Tart and snappy, the flavors of lime flesh and...   
3        US  Pineapple rind, lemon pith and orange blossom ...   
4        US  Much like the regular bottling from 2012, this...   

                          designation  points  price           province  \
0                        Vulkà Bianco      87    NaN  Sicily & Sardinia   
1                            Avidagos      87   15.0              Douro   
2                                 NaN      87   14.0             Oregon   
3                Reserve Late Harvest      87   13.0           Michigan   
4  Vintner's Reserve Wild Child Block      87   65.0             Oregon   

              region_1           region_2         taster_name  \
0                 Etna                NaN       Kerin O’Keefe   
1                  NaN                NaN          Roger Voss   
2    Willamette Valley  Willamette Valley        Paul Gregutt   
3  Lake Michigan Shore                NaN  Alexander Peartree   
4    Willamette Valley  Willamette Valley        Paul Gregutt   

  taster_twitter_handle                                              title  \
0          @kerinokeefe                  Nicosia 2013 Vulkà Bianco  (Etna)   
1            @vossroger      Quinta dos Avidagos 2011 Avidagos Red (Douro)   
2           @paulgwine       Rainstorm 2013 Pinot Gris (Willamette Valley)   
3                   NaN  St. Julian 2013 Reserve Late Harvest Riesling ...   
4           @paulgwine   Sweet Cheeks 2012 Vintner's Reserve Wild Child...   

          variety               winery  
0     White Blend              Nicosia  
1  Portuguese Red  Quinta dos Avidagos  
2      Pinot Gris            Rainstorm  
3        Riesling           St. Julian  
4      Pinot Noir         Sweet Cheeks

a) Select the first value from the description column of `reviews` and update it to `"The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity"`. Show that the data has been updated.

In [136]:
#your solution
reviews.loc[0, 'description'] = "The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity"
reviews.head()

country                                        description  \
0     Italy  The palate isn't overly expressive, offering u...   
1  Portugal  This is ripe and fruity, a wine that is smooth...   
2        US  Tart and snappy, the flavors of lime flesh and...   
3        US  Pineapple rind, lemon pith and orange blossom ...   
4        US  Much like the regular bottling from 2012, this...   

                          designation  points  price           province  \
0                        Vulkà Bianco      87    NaN  Sicily & Sardinia   
1                            Avidagos      87   15.0              Douro   
2                                 NaN      87   14.0             Oregon   
3                Reserve Late Harvest      87   13.0           Michigan   
4  Vintner's Reserve Wild Child Block      87   65.0             Oregon   

              region_1           region_2         taster_name  \
0                 Etna                NaN       Kerin O’Keefe   
1                  NaN                NaN          Roger Voss   
2    Willamette Valley  Willamette Valley        Paul Gregutt   
3  Lake Michigan Shore                NaN  Alexander Peartree   
4    Willamette Valley  Willamette Valley        Paul Gregutt   

  taster_twitter_handle                                              title  \
0          @kerinokeefe                  Nicosia 2013 Vulkà Bianco  (Etna)   
1            @vossroger      Quinta dos Avidagos 2011 Avidagos Red (Douro)   
2           @paulgwine       Rainstorm 2013 Pinot Gris (Willamette Valley)   
3                   NaN  St. Julian 2013 Reserve Late Harvest Riesling ...   
4           @paulgwine   Sweet Cheeks 2012 Vintner's Reserve Wild Child...   

          variety               winery  
0     White Blend              Nicosia  
1  Portuguese Red  Quinta dos Avidagos  
2      Pinot Gris            Rainstorm  
3        Riesling           St. Julian  
4      Pinot Noir         Sweet Cheeks

b) Select the records with index labels `1`, `2`, `3`, `5`, and `8`. Update the points of all these records to 90. Show that the data has been updated.

In [137]:
#your solution
reviews.iloc[[1, 2, 3, 5, 8], 3] = 90
reviews.iloc[[1, 2, 3, 5, 8]]

country                                        description  \
1  Portugal  This is ripe and fruity, a wine that is smooth...   
2        US  Tart and snappy, the flavors of lime flesh and...   
3        US  Pineapple rind, lemon pith and orange blossom ...   
5     Spain  Blackberry and raspberry aromas show a typical...   
8   Germany  Savory dried thyme notes accent sunnier flavor...   

            designation  points  price        province             region_1  \
1              Avidagos      90   15.0           Douro                  NaN   
2                   NaN      90   14.0          Oregon    Willamette Valley   
3  Reserve Late Harvest      90   13.0        Michigan  Lake Michigan Shore   
5          Ars In Vitro      90   15.0  Northern Spain              Navarra   
8                 Shine      90   12.0     Rheinhessen                  NaN   

            region_2         taster_name taster_twitter_handle  \
1                NaN          Roger Voss            @vossroger   
2  Willamette Valley        Paul Gregutt           @paulgwine    
3                NaN  Alexander Peartree                   NaN   
5                NaN   Michael Schachner           @wineschach   
8                NaN  Anna Lee C. Iijima                   NaN   

                                               title             variety  \
1      Quinta dos Avidagos 2011 Avidagos Red (Douro)      Portuguese Red   
2      Rainstorm 2013 Pinot Gris (Willamette Valley)          Pinot Gris   
3  St. Julian 2013 Reserve Late Harvest Riesling ...            Riesling   
5  Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...  Tempranillo-Merlot   
8  Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...      Gewürztraminer   

                winery  
1  Quinta dos Avidagos  
2            Rainstorm  
3           St. Julian  
5               Tandem  
8          Heinz Eifel

c) For all wines where region_1 is a "Valley", increase the price by 5.

In [138]:
#your solution
reviews[(reviews.region_1.str.contains("Valley")) & (~reviews.region_1.isnull())]['price'] += 5
reviews[(reviews.region_1.str.contains("Valley")) & (~reviews.region_1.isnull())].head()

C:\Users\user\AppData\Local\Temp\ipykernel_8184\3396367820.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reviews[(reviews.region_1.str.contains("Valley")) & (~reviews.region_1.isnull())]['price'] += 5


country                                        description  \
2       US  Tart and snappy, the flavors of lime flesh and...   
4       US  Much like the regular bottling from 2012, this...   
10      US  Soft, supple plum envelopes an oaky structure ...   
12      US  Slightly reduced, this wine offers a chalky, t...   
33      US  Rustic and dry, this has flavors of berries, c...   

                           designation  points  price    province  \
2                                  NaN      90   14.0      Oregon   
4   Vintner's Reserve Wild Child Block      87   65.0      Oregon   
10                      Mountain Cuvée      87   19.0  California   
12                                 NaN      87   34.0  California   
33               Puma Springs Vineyard      86   50.0  California   

             region_1           region_2     taster_name  \
2   Willamette Valley  Willamette Valley    Paul Gregutt   
4   Willamette Valley  Willamette Valley    Paul Gregutt   
10        Napa Valley               Napa  Virginie Boone   
12   Alexander Valley             Sonoma  Virginie Boone   
33   Dry Creek Valley             Sonoma             NaN   

   taster_twitter_handle                                              title  \
2            @paulgwine       Rainstorm 2013 Pinot Gris (Willamette Valley)   
4            @paulgwine   Sweet Cheeks 2012 Vintner's Reserve Wild Child...   
10               @vboone  Kirkland Signature 2011 Mountain Cuvée Caberne...   
12               @vboone  Louis M. Martini 2012 Cabernet Sauvignon (Alex...   
33                   NaN  Envolve 2010 Puma Springs Vineyard Red (Dry Cr...   

               variety              winery  
2           Pinot Gris           Rainstorm  
4           Pinot Noir        Sweet Cheeks  
10  Cabernet Sauvignon  Kirkland Signature  
12  Cabernet Sauvignon    Louis M. Martini  
33           Red Blend             Envolve

d) Split the taster name into first name and last name. Finally update taster name to be the first name only.

In [139]:
#your solution
reviews['taster_name'] = reviews['taster_name'].str.split(' ').str[0]
reviews.head()

country                                        description  \
0     Italy  The palate isn't overly expressive, offering u...   
1  Portugal  This is ripe and fruity, a wine that is smooth...   
2        US  Tart and snappy, the flavors of lime flesh and...   
3        US  Pineapple rind, lemon pith and orange blossom ...   
4        US  Much like the regular bottling from 2012, this...   

                          designation  points  price           province  \
0                        Vulkà Bianco      87    NaN  Sicily & Sardinia   
1                            Avidagos      90   15.0              Douro   
2                                 NaN      90   14.0             Oregon   
3                Reserve Late Harvest      90   13.0           Michigan   
4  Vintner's Reserve Wild Child Block      87   65.0             Oregon   

              region_1           region_2 taster_name taster_twitter_handle  \
0                 Etna                NaN       Kerin          @kerinokeefe   
1                  NaN                NaN       Roger            @vossroger   
2    Willamette Valley  Willamette Valley        Paul           @paulgwine    
3  Lake Michigan Shore                NaN   Alexander                   NaN   
4    Willamette Valley  Willamette Valley        Paul           @paulgwine    

                                               title         variety  \
0                  Nicosia 2013 Vulkà Bianco  (Etna)     White Blend   
1      Quinta dos Avidagos 2011 Avidagos Red (Douro)  Portuguese Red   
2      Rainstorm 2013 Pinot Gris (Willamette Valley)      Pinot Gris   
3  St. Julian 2013 Reserve Late Harvest Riesling ...        Riesling   
4  Sweet Cheeks 2012 Vintner's Reserve Wild Child...      Pinot Noir   

                winery  
0              Nicosia  
1  Quinta dos Avidagos  
2            Rainstorm  
3           St. Julian  
4         Sweet Cheeks

e) Find all wines tasted by taster whose first name is 5 characters long.

In [140]:
#your solution
reviews[(reviews['taster_name'].str.len() == 5)].head()

country                                        description   designation  \
0     Italy  The palate isn't overly expressive, offering u...  Vulkà Bianco   
1  Portugal  This is ripe and fruity, a wine that is smooth...      Avidagos   
6     Italy  Here's a bright, informal red that opens with ...       Belsito   
7    France  This dry and restrained wine offers spice in p...           NaN   
9    France  This has great depth of flavor with its fresh ...   Les Natures   

   points  price           province  region_1 region_2 taster_name  \
0      87    NaN  Sicily & Sardinia      Etna      NaN       Kerin   
1      90   15.0              Douro       NaN      NaN       Roger   
6      87   16.0  Sicily & Sardinia  Vittoria      NaN       Kerin   
7      87   24.0             Alsace    Alsace      NaN       Roger   
9      87   27.0             Alsace    Alsace      NaN       Roger   

  taster_twitter_handle                                              title  \
0          @kerinokeefe                  Nicosia 2013 Vulkà Bianco  (Etna)   
1            @vossroger      Quinta dos Avidagos 2011 Avidagos Red (Douro)   
6          @kerinokeefe   Terre di Giurfo 2013 Belsito Frappato (Vittoria)   
7            @vossroger              Trimbach 2012 Gewurztraminer (Alsace)   
9            @vossroger  Jean-Baptiste Adam 2012 Les Natures Pinot Gris...   

          variety               winery  
0     White Blend              Nicosia  
1  Portuguese Red  Quinta dos Avidagos  
6        Frappato      Terre di Giurfo  
7  Gewürztraminer             Trimbach  
9      Pinot Gris   Jean-Baptiste Adam

### Q2

Complete the following questions using the sample DataFrame given:

In [141]:
data = pd.DataFrame({"col1": range(3),"col2": range(3,6)})
data

col1  col2
0     0     3
1     1     4
2     2     5

a) Insert a third column, named col3, with entries 6, 9, 10

In [142]:
#your solution
data.insert(2, "col3", [6, 9, 10])
data

col1  col2  col3
0     0     3     6
1     1     4     9
2     2     5    10

b) Insert a forth row with entries 5.

In [143]:
#your solution
data.loc[3] = 5
data

col1  col2  col3
0     0     3     6
1     1     4     9
2     2     5    10
3     5     5     5

c) Swap the data in col2 and col1.

In [144]:
#your solution
data['col1'], data['col2'] = data['col2'], data['col1']
data 

col1  col2  col3
0     3     0     6
1     4     1     9
2     5     2    10
3     5     5     5

d) Drop the first two rows. This update should be reflected in `data`.

In [145]:
#your solution
data.drop([0, 1], axis = 0, inplace = True)
data

col1  col2  col3
2     5     2    10
3     5     5     5

e) Divide the elements in first row by the elements in the second row. Insert the result from the division as a new row in the dataframe as the first row.

In [146]:
#your solution
temp = (data.iloc[0] / data.iloc[1]).to_frame().T
pd.concat((temp, data), axis = 0)

col1  col2  col3
0   1.0   0.4   2.0
2   5.0   2.0  10.0
3   5.0   5.0   5.0

### Q3

There is no inbuilt insert function in pandas to insert a row of data. 

Write your own `insertRow()` function to allow a user to insert a row of data (in the form of a list) into a pandas dataframe.

You are NOT allowed to use the 2 methods described in the notes, and not allowed to use any for loops in this question.

In [182]:
def insertRow(df, index, data):
    temp1 = df[:index]
    temp2 = df[index:]
    return pd.concat((temp1, data, temp2), axis = 0)

In [185]:
#Test your code here
data = insertRow(data, 0, temp)
insertRow(data, 1, temp)

col1  col2  col3
0   1.0   0.4   2.0
0   1.0   0.4   2.0
2   5.0   2.0  10.0
3   5.0   5.0   5.0

### Q4

Use the data below to answer the questions.

In [149]:
import pandas as pd
reviews = pd.read_csv("wine.csv", index_col=0) #read in data from wine.csv
reviews.head(5) #display the first few data from the dataframe

country                                        description  \
0     Italy  Aromas include tropical fruit, broom, brimston...   
1  Portugal  This is ripe and fruity, a wine that is smooth...   
2        US  Tart and snappy, the flavors of lime flesh and...   
3        US  Pineapple rind, lemon pith and orange blossom ...   
4        US  Much like the regular bottling from 2012, this...   

                          designation  points  price           province  \
0                        Vulkà Bianco      87    NaN  Sicily & Sardinia   
1                            Avidagos      87   15.0              Douro   
2                                 NaN      87   14.0             Oregon   
3                Reserve Late Harvest      87   13.0           Michigan   
4  Vintner's Reserve Wild Child Block      87   65.0             Oregon   

              region_1           region_2         taster_name  \
0                 Etna                NaN       Kerin O’Keefe   
1                  NaN                NaN          Roger Voss   
2    Willamette Valley  Willamette Valley        Paul Gregutt   
3  Lake Michigan Shore                NaN  Alexander Peartree   
4    Willamette Valley  Willamette Valley        Paul Gregutt   

  taster_twitter_handle                                              title  \
0          @kerinokeefe                  Nicosia 2013 Vulkà Bianco  (Etna)   
1            @vossroger      Quinta dos Avidagos 2011 Avidagos Red (Douro)   
2           @paulgwine       Rainstorm 2013 Pinot Gris (Willamette Valley)   
3                   NaN  St. Julian 2013 Reserve Late Harvest Riesling ...   
4           @paulgwine   Sweet Cheeks 2012 Vintner's Reserve Wild Child...   

          variety               winery  
0     White Blend              Nicosia  
1  Portuguese Red  Quinta dos Avidagos  
2      Pinot Gris            Rainstorm  
3        Riesling           St. Julian  
4      Pinot Noir         Sweet Cheeks

a) What is the median of the `points` column in the `reviews` DataFrame?

In [188]:
#your solution
reviews.points.median()

86.0

b) What countries are represented in the dataset? (Your answer should not include any duplicates.)

In [189]:
#your solution
reviews.country.unique()

array(['Italy', 'Portugal', 'US', 'Spain', 'France', 'Germany',
       'Argentina', 'Chile', 'Australia', 'Austria'], dtype=object)

c) How often does each country appear in the dataset? Create a Series `reviews_per_country` mapping countries to the count of reviews of wines from that country.

In [193]:
#your solution
reviews_per_country = reviews.country.value_counts()
reviews_per_country

US           43
Italy        24
France       14
Chile         5
Germany       4
Spain         3
Portugal      2
Argentina     2
Australia     2
Austria       1
Name: country, dtype: int64

d) Which wine is the "best bargain"? Create a variable `bargain_wine` with the title of the wine with the highest points-to-price ratio in the dataset.

In [233]:
#your solution

temp = (reviews.points / reviews.price)
frame = pd.concat((reviews, temp.rename('ppp')), axis = 1)
bargain_wine = frame[frame.ppp == frame.ppp.max()].iloc[0]['title']
bargain_wine

'Henry Fessy 2012 Nouveau  (Beaujolais)'

e) Is a wine more likely to be "tropical" or "fruity"? Create a Series `descriptor_counts` counting how many times each of these two words appears in the description column in the dataset.

In [242]:
#your solution
trop = len(reviews[reviews['description'].str.contains('tropical')])
fruit = len(reviews[reviews['description'].str.contains('fruity')])
descriptor_counts = pd.Series({'tropical': trop, 'fruity': fruit})
descriptor_counts

tropical    4
fruity      8
dtype: int64

f) We'd like to host these wine reviews on our website, but a rating system ranging from 80 to 100 points is too hard to understand - we'd like to translate them into simple star ratings. A score of 95 or higher counts as 3 stars, a score of at least 85 but less than 95 is 2 stars. Any other score is 1 star.

Also, the Canadian Vintners Association bought a lot of ads on the site, so any wines from Canada should automatically get 3 stars, regardless of points.

Create a series star_ratings with the number of stars corresponding to each review in the dataset.

In [267]:
#your solution
import numpy as np
temp = np.where((reviews.points >= 85) & (reviews.points < 95), 2, np.where((reviews.country.str.contains('Canada')), 3, np.where((reviews.points >= 95), 3, 1))) #np.where(, 3, np.where((reviews.points >= 95), 3, ))
pd.Series(temp)

0     2
1     2
2     2
3     2
4     2
     ..
95    2
96    2
97    2
98    2
99    2
Length: 100, dtype: int32

g) For each taster, count how many reviews each person wrote.

In [269]:
#your solution
reviews.taster_name.value_counts()

Roger Voss            16
Virginie Boone        16
Kerin O’Keefe         13
Michael Schachner     10
Paul Gregutt           6
Sean P. Sullivan       6
Anna Lee C. Iijima     5
Alexander Peartree     3
Matt Kettmann          3
Joe Czerwinski         2
Jim Gordon             1
Anne Krebiehl MW       1
Name: taster_name, dtype: int64

Hence, find which revewier wrote the most review in this dataset.

In [278]:
#your solution
temp = reviews.taster_name.value_counts()
temp[temp == temp.max()]

reviews.taster_name.mode()

0        Roger Voss
1    Virginie Boone
Name: taster_name, dtype: object

h) What are the minimum and maximum prices for each variety of wine?

In [295]:
#your solution
reviews.groupby('variety').price.agg(['min', 'max']).head()

min   max
variety                               
Aglianico                   32.0  32.0
Albariño                    16.0  20.0
Bordeaux-style Red Blend    46.0  75.0
Bordeaux-style White Blend  15.0  15.0
Cabernet Franc              25.0  25.0

i) What are the most expensive wine varieties? Create a variable `sorted_varieties` containing a copy of the dataframe from the previous question where varieties are sorted in descending order based on minimum price, then on maximum price (to break ties).

In [302]:
#your solution
sorted_varieties = reviews.groupby('variety').price.agg(['min', 'max']).sort_values(by = ['min', 'max'], ascending = False)
sorted_varieties.head()

min   max
variety                             
Champagne Blend           55.0  58.0
Petite Sirah              55.0  55.0
Bordeaux-style Red Blend  46.0  75.0
Meritage                  32.0  55.0
Aglianico                 32.0  32.0

j) For each taster, find the average review score given out by that reviewer.

In [305]:
#your solution
reviews.groupby('taster_name').points.agg('mean')

taster_name
Alexander Peartree    87.000000
Anna Lee C. Iijima    86.800000
Anne Krebiehl MW      88.000000
Jim Gordon            86.000000
Joe Czerwinski        86.000000
Kerin O’Keefe         86.923077
Matt Kettmann         86.666667
Michael Schachner     86.200000
Paul Gregutt          86.500000
Roger Voss            86.437500
Sean P. Sullivan      86.333333
Virginie Boone        86.625000
Name: points, dtype: float64

k) Count the number of reviews available for each combination of countries and varieties.

For example, a Gamay produced in France has 5 reviews. Sort the values in descending order based on wine count.

In [361]:
#your solution
test = reviews.groupby(['country', 'variety']).count().sort_values(by = ['title'],ascending = False).title.to_frame()
test.head()

title
country variety                  
US      Pinot Noir              6
        Red Blend               5
        Cabernet Sauvignon      5
France  Gamay                   5
Italy   Red Blend               4

Hence, which combination of countries and varieties is most common?

In [362]:
#your solution
test.idxmax()

title    (US, Pinot Noir)
dtype: object

l) Find the average price for each combination of countries and varieties.

In [383]:
#your solution
temp = reviews.groupby(['country', 'variety']).price.mean().to_frame()
temp.head()

price
country   variety                
Argentina Malbec             21.5
Australia Chardonnay         18.0
          Rosé               20.0
Austria   Grüner Veltliner   12.0
Chile     Carmenère          12.0

Hence for each country, find the variety with the highest average price.

In [384]:
#your solution
temp.groupby('country').idxmax()

price
country                                  
Argentina             (Argentina, Malbec)
Australia               (Australia, Rosé)
Austria       (Austria, Grüner Veltliner)
Chile               (Chile, Petit Verdot)
France          (France, Champagne Blend)
Germany               (Germany, Riesling)
Italy                  (Italy, Aglianico)
Portugal       (Portugal, Portuguese Red)
Spain          (Spain, Tempranillo Blend)
US         (US, Bordeaux-style Red Blend)

### Q5

Use the data below to answer the questions.

In [385]:
import pandas as pd;
DFAmount = pd.DataFrame(data = [[4,19,13,9],[7,13,20,12],[11,16,13,5],[4,3,4,5]], columns = ['XS','S','M','L'], index = ['Shirt','Tee Shirt','Polo Shirt','V Neck Shirt'])
DFAmount

XS   S   M   L
Shirt          4  19  13   9
Tee Shirt      7  13  20  12
Polo Shirt    11  16  13   5
V Neck Shirt   4   3   4   5

In [386]:
DFSellingprice = pd.DataFrame(data = [[21.9,22.9,23.9,24.9],[23.9,23.9,25.9,25.9],[29,29,32,32],[28,28,28,28]], columns = ['XS','S','M','L'], index = ['Shirt','Tee Shirt','Polo Shirt','V Neck Shirt'])
DFSellingprice

XS     S     M     L
Shirt         21.9  22.9  23.9  24.9
Tee Shirt     23.9  23.9  25.9  25.9
Polo Shirt    29.0  29.0  32.0  32.0
V Neck Shirt  28.0  28.0  28.0  28.0

In [387]:
DFCostprice = pd.DataFrame(data = [[18.0,18,19,19],[20,20,21,21],[25,25,25,25],[20,20,22,22]], columns = ['XS','S','M','L'], index = ['Shirt','Tee Shirt','Polo Shirt','V Neck Shirt'])
DFCostprice

XS   S   M   L
Shirt         18.0  18  19  19
Tee Shirt     20.0  20  21  21
Polo Shirt    25.0  25  25  25
V Neck Shirt  20.0  20  22  22

a) Find the total cost price of the all the item in the shop.

In [394]:
#your solution
cost = (DFAmount * DFCostprice).sum().sum()
cost

3367.0

b) Find the total profit if he sold all the item.

In [395]:
#your solution
sell = DFAmount * DFSellingprice
sell.sum().sum() - cost

804.2999999999993

c) He realized that he had entered the selling price of the shirt wrongly. The selling price of the shirt in increasing sizes is 22.90, 24.90, 25.90 and 26.90 respectively. Make the necessary amendment to the DFSellingprice.

In [398]:
#your solution
DFSellingprice.loc['Shirt'] = [22.90, 24.90, 25.90, 26.90]
DFSellingprice

XS     S     M     L
Shirt         22.9  24.9  25.9  26.9
Tee Shirt     23.9  23.9  25.9  25.9
Polo Shirt    29.0  29.0  32.0  32.0
V Neck Shirt  28.0  28.0  28.0  28.0